Search.appendIndex(
    [
                {
            "fqsen": "\\Horde_Autoloader_ClassPathMapper_Application",
            "name": "Horde_Autoloader_ClassPathMapper_Application",
            "summary": "Provides\u0020a\u0020classmapper\u0020that\u0020implements\u0020generic\u0020pattern\u0020for\u0020different\nmapping\u0020types\u0020within\u0020the\u0020application\u0020directory.",
            "url": "classes/Horde-Autoloader-ClassPathMapper-Application.html"
        },                {
            "fqsen": "\\Horde_Autoloader_ClassPathMapper_Application\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/Horde-Autoloader-ClassPathMapper-Application.html#method___construct"
        },                {
            "fqsen": "\\Horde_Autoloader_ClassPathMapper_Application\u003A\u003AaddMapping\u0028\u0029",
            "name": "addMapping",
            "summary": "",
            "url": "classes/Horde-Autoloader-ClassPathMapper-Application.html#method_addMapping"
        },                {
            "fqsen": "\\Horde_Autoloader_ClassPathMapper_Application\u003A\u003AmapToPath\u0028\u0029",
            "name": "mapToPath",
            "summary": "Search\u0020for\u0020a\u0020mapping\u0020from\u0020class\u0020to\u0020file\u0020path.",
            "url": "classes/Horde-Autoloader-ClassPathMapper-Application.html#method_mapToPath"
        },                {
            "fqsen": "\\Horde_Autoloader_ClassPathMapper_Application\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "String\u0020representation\u0020of\u0020class.",
            "url": "classes/Horde-Autoloader-ClassPathMapper-Application.html#method___toString"
        },                {
            "fqsen": "\\Horde_Autoloader_ClassPathMapper_Application\u003A\u003AAPPLICATION_POS",
            "name": "APPLICATION_POS",
            "summary": "The\u0020following\u0020constants\u0020are\u0020for\u0020naming\u0020the\u0020positions\u0020in\u0020the\u0020regex\u0020for\neasy\u0020readability\u0020later.",
            "url": "classes/Horde-Autoloader-ClassPathMapper-Application.html#constant_APPLICATION_POS"
        },                {
            "fqsen": "\\Horde_Autoloader_ClassPathMapper_Application\u003A\u003AACTION_POS",
            "name": "ACTION_POS",
            "summary": "",
            "url": "classes/Horde-Autoloader-ClassPathMapper-Application.html#constant_ACTION_POS"
        },                {
            "fqsen": "\\Horde_Autoloader_ClassPathMapper_Application\u003A\u003ASUFFIX_POS",
            "name": "SUFFIX_POS",
            "summary": "",
            "url": "classes/Horde-Autoloader-ClassPathMapper-Application.html#constant_SUFFIX_POS"
        },                {
            "fqsen": "\\Horde_Autoloader_ClassPathMapper_Application\u003A\u003ANAME_SEGMENT",
            "name": "NAME_SEGMENT",
            "summary": "",
            "url": "classes/Horde-Autoloader-ClassPathMapper-Application.html#constant_NAME_SEGMENT"
        },                {
            "fqsen": "\\Horde_Autoloader_ClassPathMapper_Application\u003A\u003A\u0024_appDir",
            "name": "_appDir",
            "summary": "",
            "url": "classes/Horde-Autoloader-ClassPathMapper-Application.html#property__appDir"
        },                {
            "fqsen": "\\Horde_Autoloader_ClassPathMapper_Application\u003A\u003A\u0024_mappings",
            "name": "_mappings",
            "summary": "",
            "url": "classes/Horde-Autoloader-ClassPathMapper-Application.html#property__mappings"
        },                {
            "fqsen": "\\Horde_Autoloader_ClassPathMapper_Default",
            "name": "Horde_Autoloader_ClassPathMapper_Default",
            "summary": "Provides\u0020classmapper\u0020that\u0020maps\u0020classes\u0020to\u0020paths\u0020following\u0020the\u0020PHP\u0020Framework\nInterop\u0020Group\u0020PSR\u002D0\u0020reference\u0020implementation.",
            "url": "classes/Horde-Autoloader-ClassPathMapper-Default.html"
        },                {
            "fqsen": "\\Horde_Autoloader_ClassPathMapper_Default\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/Horde-Autoloader-ClassPathMapper-Default.html#method___construct"
        },                {
            "fqsen": "\\Horde_Autoloader_ClassPathMapper_Default\u003A\u003AmapToPath\u0028\u0029",
            "name": "mapToPath",
            "summary": "Search\u0020for\u0020a\u0020mapping\u0020from\u0020class\u0020to\u0020file\u0020path.",
            "url": "classes/Horde-Autoloader-ClassPathMapper-Default.html#method_mapToPath"
        },                {
            "fqsen": "\\Horde_Autoloader_ClassPathMapper_Default\u003A\u003A\u0024_includePath",
            "name": "_includePath",
            "summary": "",
            "url": "classes/Horde-Autoloader-ClassPathMapper-Default.html#property__includePath"
        },                {
            "fqsen": "\\Horde_Autoloader_ClassPathMapper_Prefix",
            "name": "Horde_Autoloader_ClassPathMapper_Prefix",
            "summary": "Provides\u0020a\u0020classmapper\u0020that\u0020implements\u0020generic\u0020pattern\u0020for\u0020different\nmapping\u0020types\u0020within\u0020the\u0020application\u0020directory.",
            "url": "classes/Horde-Autoloader-ClassPathMapper-Prefix.html"
        },                {
            "fqsen": "\\Horde_Autoloader_ClassPathMapper_Prefix\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor",
            "url": "classes/Horde-Autoloader-ClassPathMapper-Prefix.html#method___construct"
        },                {
            "fqsen": "\\Horde_Autoloader_ClassPathMapper_Prefix\u003A\u003AmapToPath\u0028\u0029",
            "name": "mapToPath",
            "summary": "Search\u0020for\u0020a\u0020mapping\u0020from\u0020class\u0020to\u0020file\u0020path.",
            "url": "classes/Horde-Autoloader-ClassPathMapper-Prefix.html#method_mapToPath"
        },                {
            "fqsen": "\\Horde_Autoloader_ClassPathMapper_Prefix\u003A\u003A\u0024_includePath",
            "name": "_includePath",
            "summary": "Include\u0020path.",
            "url": "classes/Horde-Autoloader-ClassPathMapper-Prefix.html#property__includePath"
        },                {
            "fqsen": "\\Horde_Autoloader_ClassPathMapper_Prefix\u003A\u003A\u0024_pattern",
            "name": "_pattern",
            "summary": "PCRE\u0020pattern\u0020to\u0020match\u0020in\u0020class.",
            "url": "classes/Horde-Autoloader-ClassPathMapper-Prefix.html#property__pattern"
        },                {
            "fqsen": "\\Horde_Autoloader_ClassPathMapper_PrefixString",
            "name": "Horde_Autoloader_ClassPathMapper_PrefixString",
            "summary": "Provides\u0020a\u0020classmapper\u0020that\u0020implements\u0020prefix\u0020matching\u0020using\u0020a\u0020simple\nstring\u0020search\u0020within\u0020a\u0020base\u0020application\u0020directory.",
            "url": "classes/Horde-Autoloader-ClassPathMapper-PrefixString.html"
        },                {
            "fqsen": "\\Horde_Autoloader_ClassPathMapper_PrefixString\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor",
            "url": "classes/Horde-Autoloader-ClassPathMapper-PrefixString.html#method___construct"
        },                {
            "fqsen": "\\Horde_Autoloader_ClassPathMapper_PrefixString\u003A\u003AmapToPath\u0028\u0029",
            "name": "mapToPath",
            "summary": "Search\u0020for\u0020a\u0020mapping\u0020from\u0020class\u0020to\u0020file\u0020path.",
            "url": "classes/Horde-Autoloader-ClassPathMapper-PrefixString.html#method_mapToPath"
        },                {
            "fqsen": "\\Horde_Autoloader_ClassPathMapper_PrefixString\u003A\u003A_ipos\u0028\u0029",
            "name": "_ipos",
            "summary": "Locale\u0020independant\u0020stripos\u0028\u0029\u0020implementation.",
            "url": "classes/Horde-Autoloader-ClassPathMapper-PrefixString.html#method__ipos"
        },                {
            "fqsen": "\\Horde_Autoloader_ClassPathMapper_PrefixString\u003A\u003A\u0024_includePath",
            "name": "_includePath",
            "summary": "Include\u0020path.",
            "url": "classes/Horde-Autoloader-ClassPathMapper-PrefixString.html#property__includePath"
        },                {
            "fqsen": "\\Horde_Autoloader_ClassPathMapper_PrefixString\u003A\u003A\u0024_prefix",
            "name": "_prefix",
            "summary": "Prefix\u0020to\u0020search\u0020for.",
            "url": "classes/Horde-Autoloader-ClassPathMapper-PrefixString.html#property__prefix"
        },                {
            "fqsen": "\\Horde_Autoloader_ClassPathMapper",
            "name": "Horde_Autoloader_ClassPathMapper",
            "summary": "Interface\u0020for\u0020autoloader\u0020class\u0020path\u0020mappers.",
            "url": "classes/Horde-Autoloader-ClassPathMapper.html"
        },                {
            "fqsen": "\\Horde_Autoloader_ClassPathMapper\u003A\u003AmapToPath\u0028\u0029",
            "name": "mapToPath",
            "summary": "Search\u0020for\u0020a\u0020mapping\u0020from\u0020class\u0020to\u0020file\u0020path.",
            "url": "classes/Horde-Autoloader-ClassPathMapper.html#method_mapToPath"
        },                {
            "fqsen": "\\Horde_Autoloader_Default",
            "name": "Horde_Autoloader_Default",
            "summary": "Default\u0020autoloader\u0020definition\u0020that\u0020uses\u0020the\u0020include\u0020path\u0020with\u0020default\nclass\u0020path\u0020mappers.",
            "url": "classes/Horde-Autoloader-Default.html"
        },                {
            "fqsen": "\\Horde_Autoloader_Default\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Horde-Autoloader-Default.html#method___construct"
        },                {
            "fqsen": "\\Horde_Autoloader",
            "name": "Horde_Autoloader",
            "summary": "Horde\u0020autoloader\u0020implementation.",
            "url": "classes/Horde-Autoloader.html"
        },                {
            "fqsen": "\\Horde_Autoloader\u003A\u003AregisterAutoloader\u0028\u0029",
            "name": "registerAutoloader",
            "summary": "Register\u0020the\u0020autoloader\u0020with\u0020PHP\u0020\u0028in\u0020a\u0020way\u0020to\u0020play\u0020well\u0020with\u0020as\u0020many\nconfigurations\u0020as\u0020possible\u0029.",
            "url": "classes/Horde-Autoloader.html#method_registerAutoloader"
        },                {
            "fqsen": "\\Horde_Autoloader\u003A\u003AloadClass\u0028\u0029",
            "name": "loadClass",
            "summary": "Loads\u0020a\u0020class\u0020into\u0020the\u0020current\u0020environment\u0020by\u0020classname.",
            "url": "classes/Horde-Autoloader.html#method_loadClass"
        },                {
            "fqsen": "\\Horde_Autoloader\u003A\u003AaddClassPathMapper\u0028\u0029",
            "name": "addClassPathMapper",
            "summary": "Adds\u0020a\u0020class\u0020path\u0020mapper\u0020to\u0020the\u0020beginning\u0020of\u0020the\u0020queue.",
            "url": "classes/Horde-Autoloader.html#method_addClassPathMapper"
        },                {
            "fqsen": "\\Horde_Autoloader\u003A\u003AaddCallback\u0028\u0029",
            "name": "addCallback",
            "summary": "Add\u0020a\u0020callback\u0020to\u0020run\u0020when\u0020a\u0020class\u0020is\u0020loaded\u0020through\u0020loadClass\u0028\u0029.",
            "url": "classes/Horde-Autoloader.html#method_addCallback"
        },                {
            "fqsen": "\\Horde_Autoloader\u003A\u003AmapToPath\u0028\u0029",
            "name": "mapToPath",
            "summary": "Search\u0020registered\u0020mappers\u0020in\u0020LIFO\u0020order.",
            "url": "classes/Horde-Autoloader.html#method_mapToPath"
        },                {
            "fqsen": "\\Horde_Autoloader\u003A\u003A_include\u0028\u0029",
            "name": "_include",
            "summary": "Include\u0020a\u0020file.",
            "url": "classes/Horde-Autoloader.html#method__include"
        },                {
            "fqsen": "\\Horde_Autoloader\u003A\u003A_fileExists\u0028\u0029",
            "name": "_fileExists",
            "summary": "Does\u0020a\u0020file\u0020exist\u003F",
            "url": "classes/Horde-Autoloader.html#method__fileExists"
        },                {
            "fqsen": "\\Horde_Autoloader\u003A\u003A_lower\u0028\u0029",
            "name": "_lower",
            "summary": "Locale\u0020independant\u0020strtolower\u0028\u0029\u0020implementation.",
            "url": "classes/Horde-Autoloader.html#method__lower"
        },                {
            "fqsen": "\\Horde_Autoloader\u003A\u003A\u0024_callbacks",
            "name": "_callbacks",
            "summary": "List\u0020of\u0020callback\u0020methods.",
            "url": "classes/Horde-Autoloader.html#property__callbacks"
        },                {
            "fqsen": "\\Horde_Autoloader\u003A\u003A\u0024_mappers",
            "name": "_mappers",
            "summary": "List\u0020of\u0020classpath\u0020mappers.",
            "url": "classes/Horde-Autoloader.html#property__mappers"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        }            ]
);
