Search.appendIndex(
    [
                {
            "fqsen": "\\Horde_Exception_LastError",
            "name": "Horde_Exception_LastError",
            "summary": "Horde\u0020exception\u0020class\u0020that\u0020accepts\u0020output\u0020of\u0020error_get_last\u0028\u0029\u0020as\u0020\u0024code\u0020and\nmask\u0020itself\u0020as\u0020that\u0020error.",
            "url": "classes/Horde-Exception-LastError.html"
        },                {
            "fqsen": "\\Horde_Exception_LastError\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Exception\u0020constructor",
            "url": "classes/Horde-Exception-LastError.html#method___construct"
        },                {
            "fqsen": "\\Horde_Exception_NotFound",
            "name": "Horde_Exception_NotFound",
            "summary": "Exception\u0020thrown\u0020if\u0020an\u0020object\u0020wasn\u0027t\u0020found.",
            "url": "classes/Horde-Exception-NotFound.html"
        },                {
            "fqsen": "\\Horde_Exception_NotFound\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/Horde-Exception-NotFound.html#method___construct"
        },                {
            "fqsen": "\\Horde_Exception_Pear",
            "name": "Horde_Exception_Pear",
            "summary": "Horde\u0020exception\u0020class\u0020that\u0020converts\u0020PEAR\u0020errors\u0020to\u0020exceptions.",
            "url": "classes/Horde-Exception-Pear.html"
        },                {
            "fqsen": "\\Horde_Exception_Pear\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Exception\u0020constructor.",
            "url": "classes/Horde-Exception-Pear.html#method___construct"
        },                {
            "fqsen": "\\Horde_Exception_Pear\u003A\u003A_getPearTrace\u0028\u0029",
            "name": "_getPearTrace",
            "summary": "Return\u0020a\u0020trace\u0020for\u0020the\u0020PEAR\u0020error.",
            "url": "classes/Horde-Exception-Pear.html#method__getPearTrace"
        },                {
            "fqsen": "\\Horde_Exception_Pear\u003A\u003AcatchError\u0028\u0029",
            "name": "catchError",
            "summary": "Exception\u0020handling.",
            "url": "classes/Horde-Exception-Pear.html#method_catchError"
        },                {
            "fqsen": "\\Horde_Exception_Pear\u003A\u003A\u0024_class",
            "name": "_class",
            "summary": "The\u0020class\u0020name\u0020for\u0020generated\u0020exceptions.",
            "url": "classes/Horde-Exception-Pear.html#property__class"
        },                {
            "fqsen": "\\Horde_Exception_PermissionDenied",
            "name": "Horde_Exception_PermissionDenied",
            "summary": "Exception\u0020thrown\u0020if\u0020any\u0020access\u0020without\u0020sufficient\u0020permissions\u0020occured.",
            "url": "classes/Horde-Exception-PermissionDenied.html"
        },                {
            "fqsen": "\\Horde_Exception_PermissionDenied\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/Horde-Exception-PermissionDenied.html#method___construct"
        },                {
            "fqsen": "\\Horde_Exception_Translation",
            "name": "Horde_Exception_Translation",
            "summary": "Horde_Exception_Translation\u0020is\u0020the\u0020translation\u0020wrapper\u0020class\u0020for\u0020Horde_Exception.",
            "url": "classes/Horde-Exception-Translation.html"
        },                {
            "fqsen": "\\Horde_Exception_Wrapped",
            "name": "Horde_Exception_Wrapped",
            "summary": "Horde\u0020exception\u0020class\u0020that\u0020can\u0020wrap\u0020and\u0020set\u0020its\u0020details\u0020from\u0020PEAR_Error,\nException,\u0020and\u0020other\u0020objects\u0020with\u0020similar\u0020interfaces.",
            "url": "classes/Horde-Exception-Wrapped.html"
        },                {
            "fqsen": "\\Horde_Exception_Wrapped\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Exception\u0020constructor.",
            "url": "classes/Horde-Exception-Wrapped.html#method___construct"
        },                {
            "fqsen": "\\Horde_Exception",
            "name": "Horde_Exception",
            "summary": "Horde\u0020base\u0020exception\u0020class.",
            "url": "classes/Horde-Exception.html"
        },                {
            "fqsen": "\\Horde\\Exception\\DetailsTrait",
            "name": "DetailsTrait",
            "summary": "",
            "url": "classes/Horde-Exception-DetailsTrait.html"
        },                {
            "fqsen": "\\Horde\\Exception\\DetailsTrait\u003A\u003AgetDetails\u0028\u0029",
            "name": "getDetails",
            "summary": "Get\u0020additional\u0020details\u0020separated\u0020from\u0020the\u0020exception\u0027s\u0020message",
            "url": "classes/Horde-Exception-DetailsTrait.html#method_getDetails"
        },                {
            "fqsen": "\\Horde\\Exception\\DetailsTrait\u003A\u003AsetDetails\u0028\u0029",
            "name": "setDetails",
            "summary": "Set\u0020additional\u0020details\u0020separated\u0020from\u0020the\u0020exception\u0027s\u0020message",
            "url": "classes/Horde-Exception-DetailsTrait.html#method_setDetails"
        },                {
            "fqsen": "\\Horde\\Exception\\DetailsTrait\u003A\u003A\u0024extraDetails",
            "name": "extraDetails",
            "summary": "",
            "url": "classes/Horde-Exception-DetailsTrait.html#property_extraDetails"
        },                {
            "fqsen": "\\Horde\\Exception\\HordeException",
            "name": "HordeException",
            "summary": "Horde\u0020base\u0020exception\u0020class.",
            "url": "classes/Horde-Exception-HordeException.html"
        },                {
            "fqsen": "\\Horde\\Exception\\HordeException\u003A\u003A\u0024details",
            "name": "details",
            "summary": "Error\u0020details\u0020that\u0020should\u0020not\u0020be\u0020part\u0020of\u0020the\u0020main\u0020exception\u0020message,\ne.g.\u0020any\u0020additional\u0020debugging\u0020information.",
            "url": "classes/Horde-Exception-HordeException.html#property_details"
        },                {
            "fqsen": "\\Horde\\Exception\\HordeException\u003A\u003A\u0024logged",
            "name": "logged",
            "summary": "Has\u0020this\u0020exception\u0020been\u0020logged\u003F",
            "url": "classes/Horde-Exception-HordeException.html#property_logged"
        },                {
            "fqsen": "\\Horde\\Exception\\HordeThrowable",
            "name": "HordeThrowable",
            "summary": "The\u0020root\u0020interface\u0020from\u0020which\u0020all\u0020Horde\u0020Exceptions\u0020must\u0020descend",
            "url": "classes/Horde-Exception-HordeThrowable.html"
        },                {
            "fqsen": "\\Horde\\Exception\\HordeThrowable\u003A\u003AgetDetails\u0028\u0029",
            "name": "getDetails",
            "summary": "Get\u0020additional\u0020details\u0020separated\u0020from\u0020the\u0020exception\u0027s\u0020message",
            "url": "classes/Horde-Exception-HordeThrowable.html#method_getDetails"
        },                {
            "fqsen": "\\Horde\\Exception\\HordeThrowable\u003A\u003AsetDetails\u0028\u0029",
            "name": "setDetails",
            "summary": "Set\u0020additional\u0020details\u0020separated\u0020from\u0020the\u0020exception\u0027s\u0020message",
            "url": "classes/Horde-Exception-HordeThrowable.html#method_setDetails"
        },                {
            "fqsen": "\\Horde\\Exception\\LastError",
            "name": "LastError",
            "summary": "Horde\u0020exception\u0020class\u0020that\u0020accepts\u0020output\u0020of\u0020error_get_last\u0028\u0029\u0020as\u0020\u0024code\u0020and\nmask\u0020itself\u0020as\u0020that\u0020error.",
            "url": "classes/Horde-Exception-LastError.html"
        },                {
            "fqsen": "\\Horde\\Exception\\LastError\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Exception\u0020constructor",
            "url": "classes/Horde-Exception-LastError.html#method___construct"
        },                {
            "fqsen": "\\Horde\\Exception\\LogThrowable",
            "name": "LogThrowable",
            "summary": "Horde\u0020extended\u0020exception\u0020interface.",
            "url": "classes/Horde-Exception-LogThrowable.html"
        },                {
            "fqsen": "\\Horde\\Exception\\LogThrowable\u003A\u003AgetLogLevel\u0028\u0029",
            "name": "getLogLevel",
            "summary": "Get\u0020the\u0020log\u0020level.",
            "url": "classes/Horde-Exception-LogThrowable.html#method_getLogLevel"
        },                {
            "fqsen": "\\Horde\\Exception\\LogThrowable\u003A\u003AsetLogLevel\u0028\u0029",
            "name": "setLogLevel",
            "summary": "Sets\u0020the\u0020log\u0020level.",
            "url": "classes/Horde-Exception-LogThrowable.html#method_setLogLevel"
        },                {
            "fqsen": "\\Horde\\Exception\\LogThrowable\u003A\u003AmarkAsLogged\u0028\u0029",
            "name": "markAsLogged",
            "summary": "Mark\u0020this\u0020exception\u0020as\u0020already\u0020logged.\u0020This\u0020cannot\u0020be\u0020undone.",
            "url": "classes/Horde-Exception-LogThrowable.html#method_markAsLogged"
        },                {
            "fqsen": "\\Horde\\Exception\\LogThrowable\u003A\u003AisLogged\u0028\u0029",
            "name": "isLogged",
            "summary": "Check\u0020if\u0020this\u0020exception\u0020has\u0020been\u0020logged.",
            "url": "classes/Horde-Exception-LogThrowable.html#method_isLogged"
        },                {
            "fqsen": "\\Horde\\Exception\\LogTrait",
            "name": "LogTrait",
            "summary": "",
            "url": "classes/Horde-Exception-LogTrait.html"
        },                {
            "fqsen": "\\Horde\\Exception\\LogTrait\u003A\u003AgetLogLevel\u0028\u0029",
            "name": "getLogLevel",
            "summary": "Get\u0020the\u0020log\u0020level.",
            "url": "classes/Horde-Exception-LogTrait.html#method_getLogLevel"
        },                {
            "fqsen": "\\Horde\\Exception\\LogTrait\u003A\u003AsetLogLevel\u0028\u0029",
            "name": "setLogLevel",
            "summary": "Sets\u0020the\u0020log\u0020level.",
            "url": "classes/Horde-Exception-LogTrait.html#method_setLogLevel"
        },                {
            "fqsen": "\\Horde\\Exception\\LogTrait\u003A\u003AmarkAsLogged\u0028\u0029",
            "name": "markAsLogged",
            "summary": "Mark\u0020this\u0020exception\u0020as\u0020already\u0020logged.\u0020This\u0020cannot\u0020be\u0020undone.",
            "url": "classes/Horde-Exception-LogTrait.html#method_markAsLogged"
        },                {
            "fqsen": "\\Horde\\Exception\\LogTrait\u003A\u003A\u0024isLogged",
            "name": "isLogged",
            "summary": "",
            "url": "classes/Horde-Exception-LogTrait.html#property_isLogged"
        },                {
            "fqsen": "\\Horde\\Exception\\LogTrait\u003A\u003A\u0024_logLevel",
            "name": "_logLevel",
            "summary": "The\u0020log\u0020level\u0020to\u0020use.\u0020A\u0020Horde_Log\u0020constant.",
            "url": "classes/Horde-Exception-LogTrait.html#property__logLevel"
        },                {
            "fqsen": "\\Horde\\Exception\\NotFound",
            "name": "NotFound",
            "summary": "Exception\u0020thrown\u0020if\u0020an\u0020object\u0020wasn\u0027t\u0020found.",
            "url": "classes/Horde-Exception-NotFound.html"
        },                {
            "fqsen": "\\Horde\\Exception\\NotFound\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/Horde-Exception-NotFound.html#method___construct"
        },                {
            "fqsen": "\\Horde\\Exception\\Pear",
            "name": "Pear",
            "summary": "Horde\u0020exception\u0020class\u0020that\u0020converts\u0020PEAR\u0020errors\u0020to\u0020exceptions.",
            "url": "classes/Horde-Exception-Pear.html"
        },                {
            "fqsen": "\\Horde\\Exception\\Pear\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Exception\u0020constructor.",
            "url": "classes/Horde-Exception-Pear.html#method___construct"
        },                {
            "fqsen": "\\Horde\\Exception\\Pear\u003A\u003A_getPearTrace\u0028\u0029",
            "name": "_getPearTrace",
            "summary": "Return\u0020a\u0020trace\u0020for\u0020the\u0020PEAR\u0020error.",
            "url": "classes/Horde-Exception-Pear.html#method__getPearTrace"
        },                {
            "fqsen": "\\Horde\\Exception\\Pear\u003A\u003AcatchError\u0028\u0029",
            "name": "catchError",
            "summary": "Exception\u0020handling.",
            "url": "classes/Horde-Exception-Pear.html#method_catchError"
        },                {
            "fqsen": "\\Horde\\Exception\\Pear\u003A\u003A\u0024_class",
            "name": "_class",
            "summary": "The\u0020class\u0020name\u0020for\u0020generated\u0020exceptions.",
            "url": "classes/Horde-Exception-Pear.html#property__class"
        },                {
            "fqsen": "\\Horde\\Exception\\PermissionDenied",
            "name": "PermissionDenied",
            "summary": "Exception\u0020thrown\u0020if\u0020any\u0020access\u0020without\u0020sufficient\u0020permissions\u0020occured.",
            "url": "classes/Horde-Exception-PermissionDenied.html"
        },                {
            "fqsen": "\\Horde\\Exception\\PermissionDenied\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/Horde-Exception-PermissionDenied.html#method___construct"
        },                {
            "fqsen": "\\Horde\\Exception\\PermissionDeniedThrowable",
            "name": "PermissionDeniedThrowable",
            "summary": "The\u0020root\u0020interface\u0020from\u0020which\u0020all\u0020Horde\u0020Exceptions\u0020must\u0020descend",
            "url": "classes/Horde-Exception-PermissionDeniedThrowable.html"
        },                {
            "fqsen": "\\Horde\\Exception\\Translation",
            "name": "Translation",
            "summary": "Horde_Exception_Translation\u0020is\u0020the\u0020translation\u0020wrapper\u0020class\u0020for\u0020Horde_Exception.",
            "url": "classes/Horde-Exception-Translation.html"
        },                {
            "fqsen": "\\Horde\\Exception\\Translation\u003A\u003A\u0024domain",
            "name": "domain",
            "summary": "The\u0020translation\u0020domain",
            "url": "classes/Horde-Exception-Translation.html#property_domain"
        },                {
            "fqsen": "\\Horde\\Exception\\Translation\u003A\u003A\u0024pearDirectory",
            "name": "pearDirectory",
            "summary": "The\u0020absolute\u0020PEAR\u0020path\u0020to\u0020the\u0020translations\u0020for\u0020the\u0020default\u0020gettext\u0020handler.",
            "url": "classes/Horde-Exception-Translation.html#property_pearDirectory"
        },                {
            "fqsen": "\\Horde\\Exception\\Wrapped",
            "name": "Wrapped",
            "summary": "Horde\u0020exception\u0020class\u0020that\u0020can\u0020wrap\u0020and\u0020set\u0020its\u0020details\u0020from\u0020PEAR_Error,\nException,\u0020and\u0020other\u0020objects\u0020with\u0020similar\u0020interfaces.",
            "url": "classes/Horde-Exception-Wrapped.html"
        },                {
            "fqsen": "\\Horde\\Exception\\Wrapped\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Exception\u0020constructor.",
            "url": "classes/Horde-Exception-Wrapped.html#method___construct"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Horde\\Exception",
            "name": "Exception",
            "summary": "",
            "url": "namespaces/horde-exception.html"
        },                {
            "fqsen": "\\Horde",
            "name": "Horde",
            "summary": "",
            "url": "namespaces/horde.html"
        }            ]
);
